"""Job Postings Skill rename unique constraint

Revision ID: 0d3c59cee439
Revises: d459fc0e66fc
Create Date: 2026-10-06 14:37:44.256075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3c59cee439'
down_revision: Union[str, Sequence[str], None] = 'd459fc0e66fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_job_postings_job_postings_id_skills_id'), 'job_postings_skills', type_='unique')
    op.create_unique_constraint('uq_job_postings_skills_job_postings_id_skills_id', 'job_postings_skills', ['job_postings_id', 'skills_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_postings_skills_job_postings_id_skills_id', 'job_postings_skills', type_='unique')
    op.create_unique_constraint(op.f('uq_job_postings_job_postings_id_skills_id'), 'job_postings_skills', ['job_postings_id', 'skills_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
