"""check constraint and enumeration for application status

Revision ID: 11351250d5b3
Revises: 0d3c59cee439
Create Date: 2026-10-07 11:24:41.535157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11351250d5b3'
down_revision: Union[str, Sequence[str], None] = '0d3c59cee439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
