"""Added Applications table

Revision ID: 12cba4df21c1
Revises: 50eeb5fa76ba
Create Date: 2026-09-20 03:04:12.215708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cba4df21c1'
down_revision: Union[str, Sequence[str], None] = '50eeb5fa76ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_postings_id', sa.UUID(), nullable=False),
    sa.Column('resumes_id', sa.UUID(), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_postings_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['resumes_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
