"""applications interviews wrapped lambda around datetime now

Revision ID: 3d539a24e5a4
Revises: e4d15f30782d
Create Date: 2026-09-22 00:34:16.820167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d539a24e5a4'
down_revision: Union[str, Sequence[str], None] = 'e4d15f30782d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
