"""updated foreign keys not nullable and fixed nullable values typing

Revision ID: 63f1056216ab
Revises: 3d539a24e5a4
Create Date: 2026-09-23 15:33:24.663980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63f1056216ab'
down_revision: Union[str, Sequence[str], None] = '3d539a24e5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('companies', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('companies', 'industry',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interviews', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interviews', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('interviews', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_postings', 'employment_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_postings', 'salary_min',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('job_postings', 'salary_max',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('job_postings', 'deadline',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'date_posted',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_postings', 'date_posted',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'deadline',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'salary_max',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('job_postings', 'salary_min',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('job_postings', 'employment_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('interviews', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interviews', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('interviews', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('companies', 'industry',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('companies', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
