"""Added job postings skills table

Revision ID: c1cd6ff6fe22
Revises: 9e5793368a42
Create Date: 2026-09-20 03:18:30.621151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cd6ff6fe22'
down_revision: Union[str, Sequence[str], None] = '9e5793368a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_postings_id', sa.UUID(), nullable=False),
    sa.Column('skills_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_postings_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings_skills')
    # ### end Alembic commands ###
