"""ck fix application status

Revision ID: c53f37904c6b
Revises: 11351250d5b3
Create Date: 2026-10-07 11:43:16.872224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.application_status import _status_values


# revision identifiers, used by Alembic.
revision: str = 'c53f37904c6b'
down_revision: Union[str, Sequence[str], None] = '11351250d5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_application_status",
        "applications",
        f"status IN ({_status_values})",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_application_status", "applications", type_="check")
    # ### end Alembic commands ###
