"""cascading deletes and uq job postings and skills

Revision ID: d459fc0e66fc
Revises: 63f1056216ab
Create Date: 2026-09-23 17:35:13.925717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd459fc0e66fc'
down_revision: Union[str, Sequence[str], None] = '63f1056216ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_resumes_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_job_postings_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key('applications_resumes_id_fkey', 'applications', 'resumes', ['resumes_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('applications_job_postings_id_fkey', 'applications', 'job_postings', ['job_postings_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cover_letters_job_postings_id_fkey'), 'cover_letters', type_='foreignkey')
    op.create_foreign_key('cover_letters_job_postings_id_fkey', 'cover_letters', 'job_postings', ['job_postings_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interviews_applications_id_fkey'), 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_applications_id_fkey', 'interviews', 'applications', ['applications_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_postings_company_id_fkey'), 'job_postings', type_='foreignkey')
    op.create_foreign_key('job_postings_company_id_fkey', 'job_postings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_job_postings_job_postings_id_skills_id', 'job_postings_skills', ['job_postings_id', 'skills_id'])
    op.drop_constraint(op.f('job_postings_skills_skills_id_fkey'), 'job_postings_skills', type_='foreignkey')
    op.drop_constraint(op.f('job_postings_skills_job_postings_id_fkey'), 'job_postings_skills', type_='foreignkey')
    op.create_foreign_key('job_postings_skills_job_postings_id_fkey', 'job_postings_skills', 'job_postings', ['job_postings_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('job_postings_skills_skills_id_fkey', 'job_postings_skills', 'skills', ['skills_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_postings_skills_skills_id_fkey'), 'job_postings_skills', type_='foreignkey')
    op.drop_constraint(op.f('job_postings_skills_job_postings_id_fkey'), 'job_postings_skills', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_skills_job_postings_id_fkey'), 'job_postings_skills', 'job_postings', ['job_postings_id'], ['id'])
    op.create_foreign_key(op.f('job_postings_skills_skills_id_fkey'), 'job_postings_skills', 'skills', ['skills_id'], ['id'])
    op.drop_constraint('uq_job_postings_job_postings_id_skills_id', 'job_postings_skills', type_='unique')
    op.drop_constraint(op.f('job_postings_company_id_fkey'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_company_id_fkey'), 'job_postings', 'companies', ['company_id'], ['id'])
    op.drop_constraint(op.f('interviews_applications_id_fkey'), 'interviews', type_='foreignkey')
    op.create_foreign_key(op.f('interviews_applications_id_fkey'), 'interviews', 'applications', ['applications_id'], ['id'])
    op.drop_constraint(op.f('cover_letters_job_postings_id_fkey'), 'cover_letters', type_='foreignkey')
    op.create_foreign_key(op.f('cover_letters_job_postings_id_fkey'), 'cover_letters', 'job_postings', ['job_postings_id'], ['id'])
    op.drop_constraint(op.f('applications_job_postings_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_resumes_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_job_postings_id_fkey'), 'applications', 'job_postings', ['job_postings_id'], ['id'])
    op.create_foreign_key(op.f('applications_resumes_id_fkey'), 'applications', 'resumes', ['resumes_id'], ['id'])
    # ### end Alembic commands ###
